openapi: 3.1.0
tags:
  - name: Oppgjørsrapport

info:
  title: Oppgjørsrapporter API
  description: |
    API for oppgjørsrapporter
    
    APIet tilgjengeliggjør oppgjørsrapporter av følgende typer:
    * Oppgjørsrapport arbeidsgiver - refusjoner fra Nav (tidl. K27),
    * Trekkoppgjør kreditor (tidl. T14), og
    * Trekkhendelser (tidl. T12)
  version: 1.1.0

servers:
  - url: https://sokos-oppgjorsrapporter.ekstern.dev.nav.no/
    description: dev
  - url: https://sokos-oppgjorsrapporter.ekstern.nav.no/
    description: prod

security:
  - Systembruker: []
  - EntraId: []

paths:
  /api/rapport/v1:
    post:
      description: |
        Søk etter oppgjørsrapporter brukeren har tilgang til.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RapportListeRequest"
        required: true
      responses:
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: object
              examples:
                Example#1:
                  value: "Uautorisert tilgang"
        "200":
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Rapport"
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
  /api/rapport/v1/{id}:
    get:
      description: |
        Hent metadata om en spesifikk rapport.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: object
              examples:
                Example#1:
                  value: "Uautorisert tilgang"
        "404":
          description: Not Found
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Rapport"
  /api/rapport/v1/{id}/arkiver:
    put:
      description: |
        Skru av/på arkivert-statusen til en spesifikk rapport.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: arkivert
          in: query
          required: false
          schema:
            type: boolean
            default: true
      responses:
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: object
              examples:
                Example#1:
                  value: "Uautorisert tilgang"
        "204":
          description: No Content
        "404":
          description: Not Found
  /api/rapport/v1/{id}/innhold:
    get:
      description: |
        Hent innhold i en spesifikk rapport.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: object
              examples:
                Example#1:
                  value: "Uautorisert tilgang"
        "406":
          description: Not Acceptable
          content:
            '*/*':
              schema:
                type: object
        "200":
          description: OK
          content:
            application/pdf:
              schema:
                type: string
                format: binary
            text/csv:
              schema:
                type: string
                format: binary
        "404":
          description: Not Found
components:
  schemas:
    RapportListeRequest:
      type: object
      properties:
        orgnr:
          description: |
            Returner kun rapporter utstedt til det angitte organisasjonsnummeret.

            Hvis `orgnr` ikke er angitt, avgjøres hvilke orgnummer det skal returneres rapporter for av hvordan brukeren er autentisert.
            
            For systembruker-autentisering brukes da i stedet orgnummeret systembrukeren er laget for ('systemuser_org').
            
            #### OBS: agent-systembruker må huske å angi `orgnr`
            For "vanlig" systembruker vil det kunne fungere greit å bruke orgnummer fra systembruker-tokenet, mens for
            "agent"-systembrukere vil det neppe gi ønsket oppførsel (da disse systembrukerne er laget for f.eks. en regnskapsfører som
            agerer på vegne av sine kunder - og da er det jo sjelden lista med rapporter for regnskapsfører-virksomheten man er
            interessert i).
            
            Det er dessverre ikke mulig å se forskjell på autentiseringstokenet mellom disse to typene systembrukere.
            
            Dette betyr at man **alltid må** huske å angi `orgnr` i request-body dersom man bruker agent-systembruker.
          type: string
          example: "983887457"
          nullable: true
        bankkonto:
          description: |
            Returner kun rapporter knyttet til den angitte bankkontoen.

            Dette parameteret er kun for Nav-intern bruk; det tillates ikke brukt ved systembruker-autentisering.
            Dette parameteret kan ikke kombineres med `orgnr`.
          type: string
          example: "12345678901"
          nullable: true
        aar:
          description: |
            Returner kun rapporter utstedt i det angitte året.

            Dette parameteret kan ikke kombineres med `fraDato` eller `tilDato`.
            Hvis verken `aar` eller `fraDato` er angitt, vil kun rapporter for inneværende år returneres.
          type: integer
          example: 2025
          nullable: true
        fraDato:
          description: |
            Returner kun rapporter utstedt på eller etter den angitte datoen.
            Når `fraDato` er angitt, kan `tilDato` også angis; er den ikke angitt, vil kun rapporter fra `fraDato` og ut samme år returneres.

            Dette parameteret kan ikke kombineres med `aar`.
            Hvis verken `aar` eller `fraDato` er angitt, vil kun rapporter for inneværende år returneres.
          type: string
          format: date
          example: "2025-11-17"
          nullable: true
        tilDato:
          description: |
            Returner kun rapporter utstedt før eller på den angitte datoen.

            Kan kun angis hvis også `fraDato` er angitt.
            Dette parameteret kan ikke kombineres med `aar`.
          type: string
          format: date
          example: "2025-12-24"
          nullable: true
        etterId:
          description: |
            Returner kun rapporter hvis "id" er større enn det angitte tallet.

            Når `etterId` er angitt, må søket være begrenset til ett spesifikt organisasjonsnr.
            Det kan enten gjøres ved at `orgnr` angis eksplisitt (uansett autentiseringsmetode),
            eller implisitt ved systembruker-autentisering (hvor manglende `orgnr` vil begrense
            søket til systembrukerens sluttbruker-organisasjon).

            Dette parameteret kan ikke kombineres med `aar`, `fraDato` eller `tilDato`.
          type: integer
          example: 17
          nullable: true
        rapportTyper:
          description: |
            Returner kun rapporter av de angitte typene.

            Hvis `rapportTyper` ikke er angitt, vil rapporter av alle typer returneres.
          type: array
          items:
            $ref: "#/components/schemas/RapportType"
          default: Alle rapport-typer
          uniqueItems: true
          example: ["ref-arbg"]
        inkluderArkiverte:
          description: |
            Sett til `true` dersom også arkiverte rapporter skal returneres.

            Hvis ikke satt, eller satt til `false`, vil arkiverte rapporter utelates fra den returnerte lista.
          type: boolean
          default: false

    RapportType:
      type: string
      enum:
        - "ref-arbg"
        - "trekk-hend"
        - "trekk-kred"
      description: |
        Inntil videre støtter APIet også input som bruker de gamle type-navnene:
        * "K27" for "ref-arbg"
        * "T12" for "trekk-hend
        * "T14" for "trekk-kred"

    Instant:
      type: string
      format: date-time
      example: "2025-11-26T12:34:56Z"

    Rapport:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        orgnr:
          type: "string"
        orgNavn:
          type: "string"
        type:
          $ref: "#/components/schemas/RapportType"
        datoValutert:
          type: "string"
          format: "date"
        bankkonto:
          type: "string"
        opprettet:
          $ref: "#/components/schemas/Instant"
        arkivert:
          type: boolean
      required:
        - "id"
        - "orgnr"
        - "type"
        - "datoValutert"
        - "opprettet"
        - "arkivert"

  securitySchemes:
    Systembruker:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Kan bruke [Altinn systembruker](https://docs.altinn.studio/nb/authorization/guides/system-vendor/system-user/);
        se [dokumentasjon](https://github.com/navikt/sokos-oppgjorsrapporter/wiki/Autentisering-og-autorisasjon) for hvordan dette kan settes opp.
    EntraId:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        For Nav-intern bruk: Bruk [Entra ID](https://docs.nais.io/auth/entra-id/) til autentisering.  Token må ha `audience` satt til `[cluster]:okonomi:sokos-oppgjorsrapporter`.
        
        For å teste APIet kan du lage et gyldig OBO-token ved å bruke wonderwall:
        - [dev-gcp](https://azure-token-generator.intern.dev.nav.no/api/obo?aud=dev-gcp:okonomi:sokos-oppgjorsrapporter)
