openapi: 3.1.0
tags:
  - name: Oppgjørsrapport

info:
  title: Oppgjørsrapporter API
  description: >
    API for oppgjørsrapporter: Refusjon arbeidsgiver (K27), Trekkoppgjør kreditor (T14), Trekkhendelser (T12)
  version: 1.0.0

servers:
  - url: https://sokos-oppgjorsrapporter.ekstern.dev.nav.no/
    description: dev
  - url: https://sokos-oppgjorsrapporter.ekstern.nav.no/
    description: prod

security:
  - bearerAuth: []

paths:
  /api/rapport/v1:
    post:
      description: >
        Hent liste med metadata om oppgjørsrapportene brukeren har tilgang til.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RapportListeRequest"
        required: true
      responses:
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: object
              examples:
                Example#1:
                  value: "Uautorisert tilgang"
        "200":
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Rapport"
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
  /api/rapport/v1/{id}:
    get:
      description: >
        Hent metadata om en spesifikk rapport.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: object
              examples:
                Example#1:
                  value: "Uautorisert tilgang"
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Rapport"
  /api/rapport/v1/{id}/arkiver:
    put:
      description: >
        Skru av/på arkivert-statusen til en spesifikk rapport.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: arkivert
          in: query
          required: false
          schema:
            type: boolean
            default: true
      responses:
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: object
              examples:
                Example#1:
                  value: "Uautorisert tilgang"
        "204":
          description: No Content
  /api/rapport/v1/{id}/innhold:
    get:
      description: >
        Hent innhold i en spesifikk rapport.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "401":
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: object
              examples:
                Example#1:
                  value: "Uautorisert tilgang"
        "406":
          description: Not Acceptable
          content:
            '*/*':
              schema:
                type: object
        "200":
          description: OK
          content:
            application/pdf:
              schema:
                type: string
                format: binary
            text/csv:
              schema:
                type: string
                format: binary
        "404":
          description: Not Found
          content:
            '*/*':
              schema:
                type: object
components:
  schemas:
    RapportListeRequest:
      type: object
      properties:
        orgnr:
          description: >
            Returner kun rapporter utstedt til det angitte organisasjonsnummeret.

            Hvis 'orgnr' ikke er angitt, avgjøres hvilke orgnummer det skal returneres rapporter for av hvordan brukeren er autentisert.
            For systembruker-autentisering brukes orgnummeret systembrukeren agerer på vegne av ('systemuser_org').
          type: string
          example: "983887457"
          nullable: true
        aar:
          description: >
            Returner kun rapporter utstedt i det angitte året.

            Dette parameteret kan ikke kombineres med "fraDato" eller "tilDato".
            Hvis verken "aar" eller "fraDato" er angitt, vil kun rapporter for inneværende år returneres.
          type: integer
          example: 2025
          nullable: true
        fraDato:
          description: >
            Returner kun rapporter utstedt på eller etter den angitte datoen.
            Når "fraDato" er angitt, kan "tilDato" også angis; er den ikke angitt, vil kun rapporter fra "fraDato" og ut samme år returneres.

            Dette parameteret kan ikke kombineres med "aar".
            Hvis verken "aar" eller "fraDato" er angitt, vil kun rapporter for inneværende år returneres.
          type: string
          format: date
          example: "2025-11-17"
          nullable: true
        tilDato:
          description: >
            Returner kun rapporter utstedt før eller på den angitte datoen.
            Blir kun tatt hensyn til dersom også "fraDato" er angitt.

            Dette parameteret kan ikke kombineres med "aar".
          type: string
          format: date
          example: "2025-12-24"
          nullable: true
        rapportTyper:
          description: >
            Returner kun rapporter av de angitte typene.

            Hvis "rapportTyper" ikke er angitt, vil rapporter av alle typer returneres.
          type: array
          items:
            $ref: "#/components/schemas/RapportType"
          default: Alle rapport-typer
          uniqueItems: true
          example: '["K27"]'
        inkluderArkiverte:
          description: >
            Sett til `true` dersom også arkiverte rapporter skal returneres.

            Hvis ikke satt, eller satt til `false`, vil arkiverte rapporter utelates fra den returnerte lista.
          type: boolean
          default: false

    RapportType:
      type: string
      enum:
        - K27
        - T12
        - T14

    Instant:
      type: string
      format: date-time

    Rapport:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        bestillingId:
          type: "integer"
          format: "int64"
        orgNr:
          type: "string"
        type:
          $ref: "#/components/schemas/RapportType"
        tittel:
          type: "string"
        datoValutert:
          type: "string"
          format: "date"
        opprettet:
          $ref: "#/components/schemas/Instant"
        arkivert:
          nullable: true
          $ref: "#/components/schemas/Instant"
      required:
        - "id"
        - "bestillingId"
        - "orgNr"
        - "type"
        - "tittel"
        - "datoValutert"
        - "opprettet"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Kan bruke [Altinn systembruker](https://docs.altinn.studio/nb/authorization/guides/system-vendor/system-user/), eller [Entra ID](https://docs.nais.io/auth/entra-id/) til autentisering.
        Token må ha `audience` satt til `[cluster]:okonomi:sokos-oppgjorsrapporter`.
        
        For å teste APIet kan du lage et gyldig OBO-token ved å bruke wonderwall:
        - [dev-gcp](https://azure-token-generator.intern.dev.nav.no/api/obo?aud=dev-gcp:okonomi:sokos-oppgjorsrapporter)
