version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "06:00"
      timezone: "Europe/Oslo"
    cooldown:
      default-days: 7
    groups:
      all-minor-updates:
        update-types:
          - "minor"
          - "patch"

  -  package-ecosystem: github-actions
     directory: "/"
     schedule:
       interval: "weekly"
     cooldown:
       default-days: 7
     groups:
       all-minor-updates:
         update-types:
           - "minor"
           - "patch"
