apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-oppgjorsrapporter
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 512Mi
  ingresses:
    - https://sokos-oppgjorsrapporter.intern.dev.nav.no
    - https://sokos-oppgjorsrapporter.ekstern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - azp_name
        #groups:
         # - id: 138d21fb-4e96-46d6-91e4-e3926aa349e5 # 0000-CA-SOKOS-MF-UTBETALING
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: sokos-oppgjorsrapporter-db
            users:
              - name: appbruker
  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - accessibleForAll: true
          atMaxAge: 600
          enabled: true
          product: utbetaling
          separator: "/"
          name: oppgjorsrapporter
      consumes:
        - name: "altinn:authorization/authorize"
  env:
