apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-oppgjorsrapporter
  namespace: oppgjorsrapporter
  labels:
    team: oppgjorsrapporter
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 512Mi
  ingresses:
    - https://sokos-oppgjorsrapporter.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "2abbcfe4-98c8-4b30-8bac-5ea1e0c6d0e1" # 0000-CA-SOKOS-MF-OPPGJORSRAPPORTER
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - accessibleForAll: true
          enabled: true
          product: utbetaling
          separator: "/"
          name: oppgjorsrapporter
      consumes:
        - name: "altinn:authorization/authorize"
        - name: "digdir:dialogporten.serviceprovider"
  tokenx:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_18
        tier: db-custom-1-3840
        diskAutoresize: true
        databases:
          - name: sokos-oppgjorsrapporter-db
            users:
              - name: appbruker
  accessPolicy:
    inbound:
      rules:
        - application: sokos-up-oppgjorsrapporter
        - application: sokos-oppgjorsrapporter-selvbetjening-frontend
    outbound:
      external:
        - host: platform.altinn.no
        - host: mpls01.adeo.no
          ports:
            - port: 1414
        - host: ereg-services.prod-fss-pub.nais.io
      rules:
        - application: logging
          namespace: nais-system
        - application: pengeflyt-pdfgen
  envFrom:
    - secret: altinn-authorization-subscription
    - secret: sokos-oppgjorsrapporter-secrets
  env:
    - name: APPLICATION_PROFILE
      value: PROD
    - name: MQ_HOST
      value: mpls01.adeo.no
    - name: MQ_PORT
      value: "1414"
    - name: MQ_MANAGER_NAME
      value: MPLS01
    - name: MQ_CHANNEL
      value: P_OPPGJORSRAPPORTER
    - name: MQ_REFUSJON_QUEUE
      value: QA.P_OPPGJORSRAPPORTER.REFUSJON_ARBG_GRLAG
    - name: EREG_URL
      value: https://ereg-services.prod-fss-pub.nais.io/
    - name: PDF_GENERATOR_URL
      value: http://pengeflyt-pdfgen
