apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-oppgjorsrapporter
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 512Mi
  ingresses:
    - https://sokos-oppgjorsrapporter.intern.dev.nav.no
    - https://sokos-oppgjorsrapporter.ekstern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "9c5b24f2-5e01-4966-adaf-bc9fb6410a32" # 0000-CA-SOKOS-MF-OPPGJORSRAPPORTER
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - accessibleForAll: true
          atMaxAge: 600 # OK med lang token-levetid i dev
          enabled: true
          product: utbetaling
          separator: "/"
          name: oppgjorsrapporter
      consumes:
        - name: "altinn:authorization/authorize"
  tokenx:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: sokos-oppgjorsrapporter-db
            users:
              - name: appbruker
  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
    outbound:
      external:
        - host: platform.tt02.altinn.no
        - host: mqls01.preprod.local
          ports:
            - port: 1413
      rules:
        - application: logging
          namespace: nais-system
        - application: ereg-services-q1
          namespace: arbeidsforhold
        - application: pengeflyt-pdfgen
  envFrom:
    - secret: altinn-authorization-subscription
    - secret: sokos-oppgjorsrapporter-secrets
  env:
    - name: MQ_HOST
      value: mqls01.preprod.local
    - name: MQ_PORT
      value: "1413"
    - name: MQ_MANAGER_NAME
      value: MQLS01
    - name: MQ_CHANNEL
      value: Q1_OPPGJORSRAPPORTER
    - name: MQ_REFUSJON_QUEUE
      value: QA.Q1_OPPGJORSRAPPORTER.REFUSJON_ARBG_GRLAG
    - name: EREG_URL
      value: https://ereg-services-q1.intern.dev.nav.no/
    - name: PDF_GENERATOR_URL
      value: http://pengeflyt-pdfgen

