SET lock_timeout = '5s';
SET statement_timeout = '5s';

SET SEARCH_PATH TO rapport;

ALTER TABLE rapport
    ADD COLUMN uuid              UUID NOT NULL DEFAULT uuidv4(),
    ADD COLUMN dialogporten_uuid UUID NULL;

CREATE TYPE varsel_system AS ENUM ('dialogporten');

CREATE TABLE varsel_behov
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rapport_id    BIGINT        NOT NULL REFERENCES rapport (id)
        ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    system        varsel_system NOT NULL,
    opprettet     TIMESTAMPTZ   NOT NULL,
    antall_forsok INTEGER       NOT NULL,
    neste_forsok  TIMESTAMPTZ   NOT NULL
);
