SET lock_timeout = '5s';

-- Unngå å plassere tabeller etc. i skjemaet 'public'.
-- Kommuniser hva slags funksjon tabellene dine holder til i. tabellnavn = domenebegrep, skjema = funksjon
CREATE SCHEMA IF NOT EXISTS rapport;
SET SEARCH_PATH TO rapport;

GRANT pg_read_all_data TO appbruker;
GRANT pg_write_all_data TO appbruker;

CREATE TYPE rapport_type AS ENUM ('K27', 'T12', 'T14');

CREATE TABLE IF NOT EXISTS rapport
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orgnr         TEXT         NOT NULL,
    type          rapport_type NOT NULL,
    tittel        TEXT         NOT NULL,
    -- "dato valutert" er strengt tatt ikke korrekt domenebegrep for T12, men
    -- siden den er under utfasing, bruker vi heller det korrekte
    -- domenebegrepet for K27+T14 enn å finne opp et ullent begrep som kan
    -- favne alle de tre rapport-typene.
    dato_valutert DATE         NOT NULL,
    opprettet     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    arkivert      TIMESTAMPTZ  NULL     DEFAULT NULL
);

CREATE TYPE rapport_format AS ENUM ('application/pdf', 'text/csv');

CREATE TABLE IF NOT EXISTS rapport_variant
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rapport_id BIGINT         NOT NULL REFERENCES rapport (id) DEFERRABLE INITIALLY DEFERRED,
    format     rapport_format NOT NULL,
    filnavn    TEXT           NOT NULL UNIQUE,
    innhold    BYTEA          NOT NULL
);

CREATE TABLE IF NOT EXISTS rapport_audit
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rapport_id BIGINT      NOT NULL REFERENCES rapport (id) DEFERRABLE INITIALLY DEFERRED,
    variant_id BIGINT      NULL REFERENCES rapport_variant (id) DEFERRABLE INITIALLY DEFERRED,
    tidspunkt  TIMESTAMPTZ NOT NULL,
    hendelse   TEXT        NOT NULL,
    brukernavn TEXT        NOT NULL,
    tekst      TEXT        NULL
);
