SET lock_timeout = '5s';
SET SEARCH_PATH TO rapport;

CREATE TABLE rapport_bestilling
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mottatt           TIMESTAMPTZ  NOT NULL,
    mottatt_fra       TEXT         NOT NULL,
    dokument          TEXT         NOT NULL,
    generer_som       rapport_type NOT NULL,
    ferdig_prosessert TIMESTAMPTZ  NULL
);

-- Unngå full tablescan for "finn en bestilling som trenger å bli prosessert"
CREATE INDEX IF NOT EXISTS rapport_bestilling_ikke_ferdig_prosessert ON rapport_bestilling (id) WHERE ferdig_prosessert IS NULL;
-- rapport_bestilling.id er allerede unik, men PostgreSQL blir vrang hvis det ikke finnes en UNIQUE constraint for hele target av en foreign key
CREATE UNIQUE INDEX ON rapport_bestilling (id, generer_som);

ALTER TABLE rapport
    ADD COLUMN bestilling_id BIGINT,
    ADD CONSTRAINT bestilling_id_not_null
        CHECK (bestilling_id IS NOT NULL)
        NOT VALID,
    ADD CONSTRAINT rapport_rapport_bestilling_fkey
        FOREIGN KEY (bestilling_id, type)
            REFERENCES rapport_bestilling (id, generer_som)
            DEFERRABLE
        NOT VALID;
