SET lock_timeout = '30s';
SET statement_timeout = '30s';

SET SEARCH_PATH TO rapport;

ALTER TABLE rapport
    -- Siden applikasjonen kun er i test ved deploy av denne endringen, synes metoden Squawk anbefaler unødvendig knotete:
    --   Add the column as nullable, backfill existing rows, and add a trigger to update the column on write instead.
    -- Det bør heller ikke være noe problem at "rapport"-tabellen låses mens unique-indexen bygges, så å måtte ha separate deploys
    -- for å først bygge index CONCURRENTLY, og deretter lage unique constraint av den blir også unødvendig knotete.
    -- squawk-ignore adding-field-with-default, disallowed-unique-constraint
    ADD COLUMN uuid              UUID NOT NULL UNIQUE DEFAULT uuidv4(),
    -- squawk-ignore disallowed-unique-constraint
    ADD COLUMN dialogporten_uuid UUID NULL UNIQUE;

CREATE TYPE varsel_system AS ENUM ('dialogporten');

CREATE TABLE varsel_behov
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rapport_id    BIGINT        NOT NULL REFERENCES rapport (id)
        ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    system        varsel_system NOT NULL,
    opprettet     TIMESTAMPTZ   NOT NULL,
    -- 32 bits bør være rikelig for å telle antall forsøk vi har gjort på å prosessere et varsel
    -- squawk-ignore prefer-bigint-over-int
    antall_forsok INTEGER       NOT NULL,
    neste_forsok  TIMESTAMPTZ   NOT NULL
);
