#!/bin/bash
# Check for uncommitted changes
if [ -z "$(git status --porcelain)" ]; then
  exit 0
fi

# Run Spotless check
./gradlew spotlessCheck -q

# Check if Spotless found any issues
if [ $? -ne 0 ]; then
  echo "Spotless found issues. Please run './gradlew spotlessApply' to fix them."
  exit 1
fi
