name: Build/test PR

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENCE'
      - 'CODEOWNERS'
      - '.gitignore'
      - '.editorconfig'
      - 'setupLocalEnvironment.sh'
      - 'dokumentasjon/**'
      - '.github/workflows/deploy.yaml'
      - '.github/workflows/manual-deploy.yaml'
      - '.github/workflows/security.yaml'
      - '.github/dependabot.yaml'

env:
  ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-pr:
    name: Build and test
    uses: navikt/pengeflyt-gha-workflows/.github/workflows/gradle-build-pr.yaml@main
    with:
      gradle-task: './gradlew build installDist'
