name: Deploy alerts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .nais/alert*
      - .github/workflows/deploy-alerts.yaml

jobs:
  deploy-alerts:
    name: Deploy to cluster
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    strategy:
      matrix:
        cluster: [ dev-gcp, prod-gcp ]

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

#      - uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b # v2
#        env:
#          CLUSTER: ${{ matrix.cluster }}
#          RESOURCE: .nais/alertmanager.yaml
#          VARS: .nais/alertmanager-${{matrix.cluster}}.json
#          PRINT_PAYLOAD: true

      - uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b # v2
        env:
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/alerterator.yaml
          VARS: .nais/alerterator-${{ matrix.cluster }}.json
          PRINT_PAYLOAD: true
