name: Deploy application manual

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - dev

env:
  TZ: Europe/Oslo

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build/test & push image
    uses: navikt/pengeflyt-gha-workflows/.github/workflows/gradle-build-push-image.yaml@main
    env:
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    secrets: inherit
    with:
      image-tag: snapshot
      gradle-task: './gradlew installDist'

  deploy-dev:
    needs: build
    name: Deploy to dev-gcp
    uses: navikt/pengeflyt-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: dev-gcp
      resource: .nais/naiserator-${{ inputs.environment }}.yaml
      image: ${{ needs.build.outputs.image }}
