name: Update Gradle Wrapper

on:
  # Se etter ny Gradle hver uke på mandag morgen
  schedule:
    - cron: "0 8 * * MON"
  # ... eller når noen trigger det manuelt
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # ratchet:actions/checkout@v4

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@512b1875f3b6270828abfe77b247d5895a2da1e5 # ratchet:gradle-update/update-gradle-wrapper-action@v2
