name: Update Gradle Wrapper

on:
  # Se etter ny Gradle hver uke på mandag morgen
  schedule:
    - cron: "0 8 * * MON"
  # ... eller når noen trigger det manuelt
  workflow_dispatch:

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
